- dist/bundle.js
- src/index.js
- src/lbryio.js
- src/redux/actions/user.js
I brought in any functions that weren't already in here, and added a way to override Lbryio methods so the desktop app can continue to use ipcRenderer
For https://github.com/lbryio/lbry-desktop/pull/1937
> updates for desktop app to use lbryinc

- dist/bundle.js
- package.json
- src/redux/actions/rewards.js
- src/rewards.js
So we can implement https://github.com/lbryio/lbry-desktop/pull/1935
> add logic for reward codes

- dist/bundle.js
- src/redux/actions/rewards.js
This is a PR proposal to add the logic again for silent fail as per issue https://github.com/lbryio/lbry-desktop/issues/2043
> #ISSUE-2043 Add logic lost in code refactor for silent fail on rewards

- dist/bundle.js
- src/rewards.js
the claims now come in ordered correctly.
I could not get it to build on Windows, just got stuck on "webpack"..probably some syntax that's specific to unix.
> remove reversal

- dist/bundle.js
- src/lbryio.js
We used to allow running local apis with an env, but those env's aren't passed into `lbryinc`.
> add setLocalApi method

- dist/bundle.js
- src/index.js
- src/redux/actions/user.js
Since we still need to fetch rewards when a users email is confirmed (and may need to do stuff in the future I think it makes more sense to separate this into it's own function `doUserCheckEmailVerified`
> add doUserCheckEmailVerified instead of using doFetchUser

- dist/bundle.js
- src/lbryio.js
@seanyesmunt @skhameneh I'll merge this in since it's a minor change. If you observe any issues, please comment here. Thanks.
> some tweaks to mobile auth for new email verification

- dist/bundle.js
- src/index.js
- src/lbryio.js
- src/redux/actions/user.js
- src/redux/reducers/user.js
- src/redux/selectors/user.js
So we can add a link for users to send to friends for referrals
> add referral link

- .babelrc
- dist/bundle.es.js
- dist/bundle.js
- package.json
- rollup.config.js
- src/index.js
- src/redux/actions/subscriptions.js
- src/redux/actions/user.js
- webpack.config.js
- yarn.lock
~4x reduction in code size for raw ES, even more so with building as a dependency.
> Add rollup es build, major cleanup

- dist/bundle.es.js
- dist/bundle.js
- src/redux/actions/cost_info.js
`stream` doesn't exist anymore.
> fix for v0.36 sdk

- dist/bundle.es.js
- dist/bundle.js
- package.json
- src/redux/actions/subscriptions.js
@seanyesmunt Could you take a closer look at the `claim_search` method and let me know if I missed anything? (a few differences to the implementation at https://github.com/lbryio/lbry-desktop/commit/2d95c5a3376cc7508990c2488bc8a93b01937e66#diff-46f44017f8353764672dbfc74b5ab7bdR237). Thanks.
> replace claim_list_by_channel with claim_search

- dist/bundle.es.js
- dist/bundle.js
- src/rewards.js
This was causing reward buttons to fail. 
Lbry.claim_list_mine() is now Lbry.claim_list()
> changes claim_list_mine to claim_list

- dist/bundle.es.js
- dist/bundle.js
- src/redux/actions/subscriptions.js
To be used with 0.38, includes new param + sorting by release time
> fix: 0.38 claim search changes

- dist/bundle.es.js
- dist/bundle.js
- src/index.js
- src/redux/actions/sync.js
- src/redux/reducers/sync.js
- src/redux/selectors/sync.js
@tzarebczan suggested we ought to be able to check this in order to selectively enable sync for those with an existing account
> adds hashChanged from sync get response

- dist/bundle.es.js
- dist/bundle.js
- package.json
- src/redux/actions/subscriptions.js
- yarn.lock
also adds webpack and bundle.js
> fix for buildURI warnings in setSubscriptionsLatest

- dist/bundle.es.js
- dist/bundle.js
- src/redux/actions/subscriptions.js
Remaining canonical url changes. Also had to fix up stuff related to subscriptions to match what I'm doing on desktop. Android uses this. It's been broken on desktop, not sure if this fixes it completely yet.
> fix: canonical url stuff

- dist/bundle.es.js
- dist/bundle.js
- src/redux/actions/sync.js
I also removed the default account stuff from `doGetSync` since we don't need that more.
> Add callbacks to `getSync`

- dist/bundle.es.js
- dist/bundle.js
- src/lbryio.js
- src/redux/actions/user.js
- src/redux/reducers/user.js
@jessopb The `Lbryio.authenticate()` function was still returning a user. Not sure if that was intended but it was causing an issue on lbry.tv. I'm now returning both.
> add back user to state when calling doAuthenticate

- dist/bundle.es.js
- dist/bundle.js
- src/redux/actions/sync.js
This better handles sync with locked wallets (which happens every time the lbrytv api server is restarted)
> trigger sync error correctly with locked wallets

- dist/bundle.es.js
- dist/bundle.js
- src/redux/actions/user.js
For https://github.com/lbryio/lbry-desktop/issues/3733
> allow preventing lbryinc calls on authenticate

- dist/bundle.es.js
- dist/bundle.js
- src/redux/actions/user.js
This seems a little weird passing the value through `doAuthenticate`, but it's needed for https://github.com/lbryio/lbry-desktop/issues/3812
> add callback param for doAuthenticate that returns the status

- dist/bundle.es.js
- dist/bundle.js
- src/index.js
- src/redux/selectors/rewards.js
This will allow those with multiple youtube channels to claim their rewards
> add claim code selector

- dist/bundle.es.js
- flow-typed/User.js
- src/index.js
- src/redux/actions/user.js
For https://github.com/lbryio/lbry-desktop/pull/4294
> add country to User and create doUserSetCountry

- dist/bundle.es.js
- dist/bundle.js
- src/index.js
- src/redux/selectors/blacklist.js
- src/redux/selectors/filtered.js
We were calculating these over and over in a make... selector. Let's not.
> selectors for blocklist objects

- dist/bundle.es.js
- dist/bundle.js
- src/redux/actions/sync.js
forward sync error message when available
> propagate sync password error
